name: CI/CD counter app

on:
  pull_request:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME: ${{ secrets.HOSTNAME  }}
            USER_NAME: ${{ secrets.USER_NAME  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          #Now we have got the access of EC2 and we will start the deploy .
          hostname
          cd /home/ec2-user/thd &&
          git checkout main &&
          git fetch --all &&
          git pull origin dev &&
          python3 main.py && exit
          '
           